- name: Install Miscellaneous Packages
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge {{ item.name }}' creates={{ item.creates }}
  with_items:
    - name: iproute2
      creates: /mnt/gentoo/bin/ip
    - name: vim
      creates: /mnt/gentoo/usr/bin/vim
    - name: git
      creates: /mnt/gentoo/usr/bin/git
    - name: screen
      creates: /mnt/gentoo/usr/bin/screen
