- name: Remove System Packages
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge -C {{ item.name }}'
  with_items:
    - name: sys-fs/udev

- name: Install System Packages
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge {{ item.name }}' creates={{ item.creates }}
  with_items:
    - name: eix
      creates: /mnt/gentoo/usr/bin/eix
    - name: chrony
      creates: /mnt/gentoo/etc/init.d/chronyd
    - name: grub
      creates: /mnt/gentoo/usr/sbin/grub2-install
    - name: systemd
      creates: /mnt/gentoo/usr/lib/systemd/systemd
    - name: lvm2
      creates: /mnt/gentoo/sbin/lvs

- name: Add chrony to Default Run Configuration
  command: chroot /mnt/gentoo bash -c 'systemctl enable chronyd'

- name: Add networkd to Default Run Configuration
  command: chroot /mnt/gentoo bash -c 'systemctl enable systemd-networkd'

- name: Add sshd.socket to Default Run Configuration
  command: chroot /mnt/gentoo bash -c 'systemctl enable sshd.socket'

- name: Remount /dev to get /dev/mapper visible
  command: mount --rbind /dev /mnt/gentoo/dev

- name: Configure grub Defaults
  copy: src=grub_default dest=/mnt/gentoo/etc/default/grub mode=0644 owner=root group=root

- name: Install Grub to Boot Drive
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; grub2-install {{ main_disk }}'

- name: Configure Grub Make Config
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; grub2-mkconfig -o /boot/grub/grub.cfg'

- name: Set Root Password
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; echo "root:{{ root_passwd }}" | /usr/sbin/chpasswd'


